version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/wordpress:/var/www/wordpress

  app:
    build: ./app
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./data/wordpress:/var/www/wordpress

  db:
    image: mysql:5.7.22
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
