version: '3'
services:
  web:
    image: nginx:1.15.1-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html

  app:
    image: php:7.2.7-fpm-alpine3.7
    volumes:
      - ./data/html:/var/www/html
